### ISSUE TITLE
Warnings: CalendarEventTitle and CalendarDateFormatter missing

### ISSUE THREAD

**Issue by giorgi-pro** [mattlewis92/angular2-calendar#64] opened 2016-09-28 17:13 UTC
I download the module from npm and receive these warnings: 
export 'CalendarEventTitle' was not found in 'angular2-calendar'
export 'CalendarDateFormatter' was not found in 'angular2-calendar'

I'm developing the application using:

angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64

Thank you

**Comment by mattlewis92** [comment] 2016-09-28 17:20
Are you on `0.2.6` of this library? 

It works fine in my [demo app](https://github.com/mattlewis92/angular2-tv-tracker/blob/master/src/app/app.module.ts#L9) which is built on a similar architecture as the CLI so I'm not sure what the problem might be without a repro.

**Comment by giorgi-pro** [comment] 2016-09-28 18:25
yes, looks like 0.2.6. in the demo I see the sources are imported, I mean ones from the src folder. maybe there's an issue with the package. I tried it several times, even in the clean ng project, but exactly the same warning

**Comment by mattlewis92** [comment] 2016-09-28 20:00
I've managed to reproduce the issue on a fresh CLI project, everything still works, it just generates a warning which I think it fixed in a later beta of webpack: https://github.com/webpack/webpack/issues/2977

Looks like the CLI team have [already upgraded](https://github.com/angular/angular-cli/commit/5431abc8457b436e68799f481d0d40c4cdcb29e2) to it, so the problem should resolve itself on the next release of the CLI (let me know if it doesn't)

**Closed by mattlewis92** 2016-09-28 20:00 UTC

**Comment by giorgi-pro** [comment] 2016-09-28 20:06
![image](https://cloud.githubusercontent.com/assets/8410406/18930298/ccb63da0-85c7-11e6-9741-16fb5b0e4411.png)

just FYI. thank you. cheers

**Comment by mattlewis92** [comment] 2016-09-28 20:08
You're missing the CSS import btw
```
import 'angular2-calendar/dist/css/angular2-calendar.css';
```

**Comment by gh0st** [comment] 2016-10-12 18:21
@mattlewis92 in which file should we be doing in import of the css?

**Comment by mattlewis92** [comment] 2016-10-12 18:23
Any file that you like as the styles will be available globally, as long as it's only imported once. In my playground app I just import the styles at the start of my main app module: https://github.com/mattlewis92/angular2-tv-tracker/blob/master/src/app/app.module.ts#L5

**Comment by gh0st** [comment] 2016-10-12 18:34
@mattlewis92 I get this error when using angular-cli
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'anguar2-calendar/angular2-calendar.css' in '/Users/chad/Developer/pcp-calibra/src/app'
 @ ./src/app/app.module.ts 15:0-48
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

**Comment by mattlewis92** [comment] 2016-10-12 18:50
You're using the wrong path, it should be `angular2-calendar/dist/css/angular2-calendar.css` not `anguar2-calendar/angular2-calendar.css`
